### ISSUE TITLE
Screenshot is not working

### ISSUE THREAD

**Issue by karthikeyanmarutham** [adaptant-labs/flutter_windowmanager#35]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.2 23C64 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.3)
[✓] VS Code (version 1.69.2)
[✓] VS Code (version 1.86.0-insider)
[✓] Network resources

! Doctor found issues in 1 category.

Code Details : 

Open Button
---------------
onTap() async {
  await FlutterWindowManager.addFlags(FlutterWindowManager.FLAG_SECURE);
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => ViewProfileImage(url),
          fullscreenDialog: true,
        ),
      );
}

Back Button
---------------
BackButton(
onPressed: () async {
            await FlutterWindowManager.clearFlags(
                FlutterWindowManager.FLAG_SECURE);
            SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
              Navigator.pop(context);
            });
          },
)
   

Error Details : 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method addFlags on channel flutter_windowmanager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      FlutterWindowManager.addFlags (package:flutter_windowmanager/flutter_windowmanager.dart:111:12)
<asynchronous suspension>
#2      ImageWidget.build.<anonymous closure>.<anonymous closure> (/modules/common/Widgets/MaterialWidget/image_widget.dart:98:17)
<asynchronous suspension>

**Comment by khaledelsherbiny** [comment]
I've same issue
